import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import DashboardLayoutClient from "@/components/layout/DashboardLayoutClient";
import { cookies } from "next/headers";
import { createClient } from "@/utils/supabase/server";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Expose as a CSS variable for Tailwind
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //Supabase User
  const cookieStore = await cookies();
  const supabase = await createClient(cookieStore);
  const {data:{user}} = await supabase.auth.getUser();
  return (
    <html lang="en" className={`${inter.variable} ${geistMono.variable} h-full antialiased`}>
      <body>
        <DashboardLayoutClient user={user}> {children}</DashboardLayoutClient>
      </body>
    </html>
  );
}
