/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";

export const publicAnimalsSchema = z.union([
  z.literal("cat"),
  z.literal("cow"),
  z.literal("dog"),
  z.literal("rabbit"),
  z.literal("hamster"),
  z.literal("horse"),
  z.literal("other"),
  z.literal("lizard"),
]);

export const jsonSchema = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicPetsRowSchema = z.object({
  birth_date: z.string().nullable(),
  breed: z.string().nullable(),
  color: z.string().nullable(),
  created_at: z.string(),
  height: z.number().nullable(),
  id: z.string(),
  image: z.string().nullable(),
  name: z.string(),
  notes: z.string().nullable(),
  owner_id: z.string(),
  type: publicAnimalsSchema,
  updated_at: z.string().nullable(),
  weight: z.number().nullable(),
});

export const publicPetsInsertSchema = z.object({
  birth_date: z.string().optional().nullable(),
  breed: z.string().optional().nullable(),
  color: z.string().optional().nullable(),
  created_at: z.string().optional(),
  height: z.float32().optional().nullable(),
  id: z.string().optional(),
  image: z.string().optional().nullable(),
  name: z.string(),
  notes: z.string().optional().nullable(),
  owner_id: z.string(),
  type: publicAnimalsSchema,
  updated_at: z.string().optional().nullable(),
  weight: z.number().int("Weight Must Be An Integer").optional().nullable(),
});

export const publicPetsUpdateSchema = z.object({
  birth_date: z.string().optional().nullable(),
  breed: z.string().optional().nullable(),
  color: z.string().optional().nullable(),
  created_at: z.string().optional(),
  height: z.number().optional().nullable(),
  id: z.string().optional(),
  image: z.string().optional().nullable(),
  name: z.string().optional(),
  notes: z.string().optional().nullable(),
  owner_id: z.string().optional(),
  type: publicAnimalsSchema.optional(),
  updated_at: z.string().optional().nullable(),
  weight: z.number().optional().nullable(),
});

export type PublicAnimals = z.infer<typeof publicAnimalsSchema>;
export type Json = z.infer<typeof jsonSchema>;
export type PublicPetsRow = z.infer<typeof publicPetsRowSchema>;
export type PublicPetsInsert = z.infer<typeof publicPetsInsertSchema>;
export type PublicPetsUpdate = z.infer<typeof publicPetsUpdateSchema>;
