/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";

export const publicAnimalsSchema = z.union([
  z.literal("cat"),
  z.literal("cow"),
  z.literal("dog"),
  z.literal("rabbit"),
  z.literal("hamster"),
  z.literal("horse"),
  z.literal("other"),
  z.literal("lizard"),
]);

export const publicReminderCategorySchema = z.union([
  z.literal("vaccination"),
  z.literal("appointment"),
  z.literal("medication"),
  z.literal("test"),
  z.literal("other"),
]);

export const jsonSchema: z.ZodTypeAny = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicMedicalRecordsRowSchema = z.object({
  coggins: z.boolean(),
  createdAt: z.string(),
  date: z.string(),
  description: z.string(),
  height: z.number().nullable(),
  id: z.string(),
  notes: z.string().nullable(),
  pet_id: z.string(),
  trimmed: z.boolean(),
  updatedAt: z.string().nullable(),
  vet: z.string().nullable(),
  weight: z.number().nullable(),
  wormed: z.boolean(),
  yearly_vaccines: z.boolean(),
});

export const publicMedicalRecordsInsertSchema = z.object({
  coggins: z.boolean(),
  createdAt: z.string().optional(),
  date: z.string(),
  description: z.string(),
  height: z.number().optional().nullable(),
  id: z.string().optional(),
  notes: z.string().optional().nullable(),
  pet_id: z.string(),
  trimmed: z.boolean(),
  updatedAt: z.string().optional().nullable(),
  vet: z.string().optional().nullable(),
  weight: z.number().optional().nullable(),
  wormed: z.boolean(),
  yearly_vaccines: z.boolean(),
});

export const publicMedicalRecordsUpdateSchema = z.object({
  coggins: z.boolean().optional(),
  createdAt: z.string().optional(),
  date: z.string().optional(),
  description: z.string().optional(),
  height: z.number().optional().nullable(),
  id: z.string().optional(),
  notes: z.string().optional().nullable(),
  pet_id: z.string().optional(),
  trimmed: z.boolean().optional(),
  updatedAt: z.string().optional().nullable(),
  vet: z.string().optional().nullable(),
  weight: z.number().optional().nullable(),
  wormed: z.boolean().optional(),
  yearly_vaccines: z.boolean().optional(),
});

export const publicMedicalRecordsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("medical_records_pet_id_fkey"),
    columns: z.tuple([z.literal("pet_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("pets"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicPetsRowSchema = z.object({
  birth_date: z.string().nullable(),
  breed: z.string().nullable(),
  color: z.string().nullable(),
  created_at: z.string(),
  height: z.number().nullable(),
  id: z.string(),
  image: z.string().nullable(),
  name: z.string(),
  notes: z.string().nullable(),
  owner_id: z.string(),
  type: publicAnimalsSchema,
  updated_at: z.string().nullable(),
  weight: z.number().nullable(),
});

export const publicPetsInsertSchema = z.object({
  birth_date: z.string().optional().nullable(),
  breed: z.string().optional().nullable(),
  color: z.string().optional().nullable(),
  created_at: z.string().optional(),
  height: z.number().optional().nullable(),
  id: z.string().optional(),
  image: z.string().optional().nullable(),
  name: z.string(),
  notes: z.string().optional().nullable(),
  owner_id: z.string(),
  type: publicAnimalsSchema,
  updated_at: z.string().optional().nullable(),
  weight: z.number().optional().nullable(),
});

export const publicPetsUpdateSchema = z.object({
  birth_date: z.string().optional().nullable(),
  breed: z.string().optional().nullable(),
  color: z.string().optional().nullable(),
  created_at: z.string().optional(),
  height: z.number().optional().nullable(),
  id: z.string().optional(),
  image: z.string().optional().nullable(),
  name: z.string().optional(),
  notes: z.string().optional().nullable(),
  owner_id: z.string().optional(),
  type: publicAnimalsSchema.optional(),
  updated_at: z.string().optional().nullable(),
  weight: z.number().optional().nullable(),
});

export const publicReminderHistoryRowSchema = z.object({
  category: publicReminderCategorySchema,
  completed_at: z.string(),
  created_at: z.string(),
  id: z.string(),
  notes: z.string().nullable(),
  pet_id: z.string(),
  title: z.string(),
});

export const publicReminderHistoryInsertSchema = z.object({
  category: publicReminderCategorySchema,
  completed_at: z.string(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  notes: z.string().optional().nullable(),
  pet_id: z.string(),
  title: z.string(),
});

export const publicReminderHistoryUpdateSchema = z.object({
  category: publicReminderCategorySchema.optional(),
  completed_at: z.string().optional(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  notes: z.string().optional().nullable(),
  pet_id: z.string().optional(),
  title: z.string().optional(),
});

export const publicReminderHistoryRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("reminder_history_pet_id_fkey"),
    columns: z.tuple([z.literal("pet_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("pets"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicRemindersRowSchema = z.object({
  category: publicReminderCategorySchema,
  created_at: z.string(),
  date_completed: z.string().nullable(),
  description: z.string().nullable(),
  due_date: z.string(),
  id: z.string(),
  is_recurring: z.boolean(),
  last_notified_at: z.string().nullable(),
  pet_id: z.string(),
  recurrence_interval: z.number().nullable(),
  recurrence_period: z.string().nullable(),
  title: z.string(),
  updated_at: z.string(),
});

export const publicRemindersInsertSchema = z.object({
  category: publicReminderCategorySchema.optional(),
  created_at: z.string().optional(),
  date_completed: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  due_date: z.string(),
  id: z.string().optional(),
  is_recurring: z.boolean().optional(),
  last_notified_at: z.string().optional().nullable(),
  pet_id: z.string(),
  recurrence_interval: z.number().optional().nullable(),
  recurrence_period: z.string().optional().nullable(),
  title: z.string(),
  updated_at: z.string().optional(),
});

export const publicRemindersUpdateSchema = z.object({
  category: publicReminderCategorySchema.optional(),
  created_at: z.string().optional(),
  date_completed: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  due_date: z.string().optional(),
  id: z.string().optional(),
  is_recurring: z.boolean().optional(),
  last_notified_at: z.string().optional().nullable(),
  pet_id: z.string().optional(),
  recurrence_interval: z.number().optional().nullable(),
  recurrence_period: z.string().optional().nullable(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicRemindersRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("reminders_pet_id_fkey"),
    columns: z.tuple([z.literal("pet_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("pets"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export type PublicAnimals = z.infer<typeof publicAnimalsSchema>;
export type PublicReminderCategory = z.infer<
  typeof publicReminderCategorySchema
>;
export type Json = z.infer<typeof jsonSchema>;
export type PublicMedicalRecordsRow = z.infer<
  typeof publicMedicalRecordsRowSchema
>;
export type PublicMedicalRecordsInsert = z.infer<
  typeof publicMedicalRecordsInsertSchema
>;
export type PublicMedicalRecordsUpdate = z.infer<
  typeof publicMedicalRecordsUpdateSchema
>;
export type PublicMedicalRecordsRelationships = z.infer<
  typeof publicMedicalRecordsRelationshipsSchema
>;
export type PublicPetsRow = z.infer<typeof publicPetsRowSchema>;
export type PublicPetsInsert = z.infer<typeof publicPetsInsertSchema>;
export type PublicPetsUpdate = z.infer<typeof publicPetsUpdateSchema>;
export type PublicReminderHistoryRow = z.infer<
  typeof publicReminderHistoryRowSchema
>;
export type PublicReminderHistoryInsert = z.infer<
  typeof publicReminderHistoryInsertSchema
>;
export type PublicReminderHistoryUpdate = z.infer<
  typeof publicReminderHistoryUpdateSchema
>;
export type PublicReminderHistoryRelationships = z.infer<
  typeof publicReminderHistoryRelationshipsSchema
>;
export type PublicRemindersRow = z.infer<typeof publicRemindersRowSchema>;
export type PublicRemindersInsert = z.infer<typeof publicRemindersInsertSchema>;
export type PublicRemindersUpdate = z.infer<typeof publicRemindersUpdateSchema>;
export type PublicRemindersRelationships = z.infer<
  typeof publicRemindersRelationshipsSchema
>;
